//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up1_antusevich_al
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public int ЗаявкаID { get; set; }
        public Nullable<int> КлиентID { get; set; }
        public Nullable<int> ОборудованиеID { get; set; }
        public System.DateTime ДатаСоздания { get; set; }
        public string Описание { get; set; }
        public string Статус { get; set; }
        public Nullable<int> РаботникID { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Оборудование Оборудование { get; set; }
        public virtual Работники Работники { get; set; }
    }
}
